# terination 16.667 total
---
apiVersion: v1
kind: Pod
metadata:
  name: debian-slim
spec:
  containers:
  - name: main
    image: docker.io/debian:buster-slim
    command:
    - bash
    - -c
    - 'sleep infinity'
  terminationGracePeriodSeconds: 3
