---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: args-def
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                }, {
                    "type": "route-override"
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: args
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "args-def",
              "ips": [ "10.1.1.102/24" ],
              "cni-args": {
                  "addroutes": [ {
                      "dst": "192.168.0.0/24",
                      "gw": "10.1.1.254"
                  } ]
              }
            }
    ]'
