---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "type": "bridge",
            "bridge": "testbr1",
            "hairpinMode": true,
            "ipam": {
                "type": "host-local"
                "ranges": [
                    [
                        {
                            "subnet": "10.10.0.0/16",
                            "rangeStart": "10.10.1.20",
                            "rangeEnd": "10.10.3.50",
                            "gateway": "10.10.0.254"
                        },
                    ]
                ],
                "dataDir": "/var/lib/cni/testbr1"
            }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: bridge
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "bridge" }
    ]'
