apiVersion: v1
kind: Pod
metadata:
  name: centos
  annotations:
spec:
  containers:
  - name: centos
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true

