---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: gateway
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static",
                        "routes": [
                            {
                              "dst": "0.0.0.0/0",
                              "gw": "10.1.1.1"
                            }
                        ]
                    }
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: gateway
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "gateway",
              "ips": [ "10.1.1.103/24" ],
              "default-route": [ "10.1.1.1" ]
            }
    ]'
