---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "master": "eth1",
            "mode": "bridge",
            "ipam": {
                "type": "dhcp"
            }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: macvlan-dhcp
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-dhcp" }
    ]'
