---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: runtimeconfig-mac
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                }, {
                    "capabilities": { "mac": true },
                    "type": "tuning"
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: runtimeconfig-mac
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "runtimeconfig-mac",
              "ips": [ "10.1.1.104/24" ],
              "mac": "c2:b0:57:49:47:f1" }
    ]'
