---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: tuning
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "bridge",
                    "capabilities": { "ips": true },
                    "bridge": "testbr1",
                    "ipam": {
                        "type": "static"
                    }
                }, {
                    "capabilities": { "mac": true },
                    "type": "tuning",
                    "sysctl": {
                            "net.ipv6.conf.default.accept_ra" : "2"
                    }
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: tuning
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "tuning",
              "ips": [ "11.1.1.104/24" ],
              "mac": "c2:b0:57:49:47:f1" }
    ]'
